### ISSUE TITLE
Improvements Suggestion

### ISSUE THREAD

**Issue by NewGuitarWhoDis** [Flye001/Website#2]
Add: 

`-webkit-touch-callout: none; /* iOS Safari */`

`-webkit-user-select: none; /* Safari */`

`-khtml-user-select: none; /* Konqueror HTML */`

`-moz-user-select: none; /* Old versions of Firefox */`

`-ms-user-select: none; /* Internet Explorer/Edge */`

`user-select: none; /* Non-prefixed version, currently supported by Chrome, Edge, Opera and Firefox */`

**Comment by Flye001** [comment]
Thanks for the suggestion! I've done it with tailwind instead (https://tailwindcss.com/docs/user-select)
